# Generated by Django 5.2.17 on 2026-09-21 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activation_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Преподаватель, которому принадлежит ученик.', limit_choices_to={'profile__role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
