# Generated by Django 5.2.17 on 2026-09-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_assignment_attachment_remove_material_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_for_grade',
            field=models.BooleanField(default=True, help_text='Если выключено, задание не влияет на рейтинг и не оценивается.', verbose_name='На оценку'),
        ),
    ]
