# Generated by Django 5.2.17 on 2026-09-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_assignment_is_for_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='formal_grade',
            field=models.CharField(blank=True, choices=[('poor', 'Плохо'), ('satisfactory', 'Удовлетворительно'), ('good', 'Хорошо'), ('excellent', 'Отлично')], help_text='Формальная оценка для заданий без баллов.', max_length=20),
        ),
    ]
