# Generated by Django 5.2.17 on 2026-09-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_submission_formal_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Закрытое задание нельзя открыть, пока преподаватель не откроет или не сработает автооткрытие.', verbose_name='Закрыто для ученика'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='overdue_processed',
            field=models.BooleanField(default=False, help_text='Служебное: автооценка 0 и уведомления о просрочке уже выставлены.', verbose_name='Просрочка обработана'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='unlock_at',
            field=models.DateTimeField(blank=True, help_text='Если задание закрыто, оно откроется автоматически в это время.', null=True, verbose_name='Автооткрытие'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('submission', 'Сдача работы'), ('material', 'Новая теория'), ('assignment', 'Новое задание'), ('assignment_open', 'Открытие задания'), ('overdue', 'Просрочка'), ('grade', 'Оценка'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
