# Generated by Django 5.2.17 on 2026-09-21 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_assignment_lock_and_overdue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Обязательно для зачёта.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Время на зачёт (мин)'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instruction',
            field=models.TextField(blank=True, help_text='Подробная инструкция для зачёта (видна после начала).', verbose_name='Инструкция'),
        ),
        migrations.AddField(
            model_name='submission',
            name='exam_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='exam_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
